version: '{build}'
image: Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
  - fb_download: https://www.dropbox.com/s/x46uy7e5zrtsnux/fb30.7z?dl=1
    fb_start: .\firebird.exe -a

  - fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
    fb_start: .\bin\fb_inet_server.exe -a -m

#  - fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
#    fb_start: .\bin\fb_inet_server.exe -a
shallow_clone: true
test: off
before_build:
  - ps: nuget restore Provider\src\NETProvider.sln
build:
  project: Provider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
before_test:
  - ps: $sourceDir = Resolve-Path .
  - ps: $testsDir = "$sourceDir\Provider\src\FirebirdSql.Data.UnitTests\bin\$env:Configuration"

  - ps: mkdir C:\firebird | Out-Null
  - ps: cd C:\firebird
  - ps: Start-FileDownload "$env:fb_download" | Out-Null
  - ps: 7z x ($env:fb_download -replace '.+/([^/]+)\?dl=1','$1')
  - ps: mv .\embedded\* $testsDir
  - ps: mv .\server\* .
  - ps: rmdir .\embedded
  - ps: rmdir .\server

  - ps: iex $env:fb_start
  - ps: ni firebird.log -ItemType File | Out-Null
test_script:
  - ps: cd $testsDir
  - ps: nunit3-console FirebirdSql.Data.UnitTests.dll --framework=net-4.5 --result='myresults.xml;format=AppVeyor'
artifacts:
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\NET45\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\NET45\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\NET40\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\NET40\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard1.6\FirebirdSql.Data.FirebirdClient.dll
  - path: Provider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\netstandard1.6\FirebirdSql.Data.FirebirdClient.pdb
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\NET45\EntityFramework.Firebird.dll
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\NET45\EntityFramework.Firebird.pdb
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\NET40\EntityFramework.Firebird.dll
  - path: Provider\src\EntityFramework.Firebird\bin\$(Configuration)\NET40\EntityFramework.Firebird.pdb