version: '0.0.0.{build}'
image: Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
  - name: FB 3.0 (Default)
    fb_download: https://www.dropbox.com/s/x46uy7e5zrtsnux/fb30.7z?dl=1
    fb_start: .\firebird.exe -a

  - name: FB 2.5 (SC)
    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
    fb_start: .\bin\fb_inet_server.exe -a -m

#  - name: FB 2.5 (CS)
#    fb_download: https://www.dropbox.com/s/ayzjnxjx20vb7s5/fb25.7z?dl=1
#    fb_start: .\bin\fb_inet_server.exe -a
test: off
init:
  - git config --global core.autocrlf true
before_build:
  - ps: $baseDir = Resolve-Path .
build_script:
  - ps: $env:build_nuget = 'C:\Program Files\AppVeyor\BuildAgent\Tools\nuget.exe'
  - ps: $env:build_wix = 'C:\Program Files (x86)\WiX Toolset v3.11\bin'
  - ps: "& $baseDir\\Provider\\build.ps1 -Configuration $env:CONFIGURATION -Version $env:APPVEYOR_BUILD_VERSION"
after_build:
  - ps: gci "$baseDir\Provider\out" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
  - ps: $env:tests_firebird_dir = 'C:\firebird'
  - ps: $env:tests_result_format = 'AppVeyor'
  - ps: "& $baseDir\\Provider\\tests.ps1 -Configuration $env:CONFIGURATION -FbDownload $env:fb_download -FbStart $env:fb_start"
