version: 0.0.0.{build}
os: Default Azure
configuration:
  - Debug
  - Release_40
  - Release_45
shallow_clone: true
matrix:
  fast_finish: true
before_test:
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/firebird/firebird-win32/2.5.4-Release/Firebird-2.5.4.26856-0_Win32.zip" | Out-Null
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/firebird/firebird-win64/2.5.4-Release/Firebird-2.5.4.26856-0_x64_embed.zip" | Out-Null
  - ps: $sourceDir = (Resolve-Path .).Path
  - ps: $targetDir = "$sourceDir\NETProvider\src\FirebirdSql.Data.UnitTests\bin\$env:Configuration"
  - ps: '[System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem") | Out-Null'
  - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("$sourceDir\Firebird-2.5.4.26856-0_x64_embed.zip", $targetDir) | Out-Null'
  - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("$sourceDir\Firebird-2.5.4.26856-0_Win32.zip", "c:\firebird") | Out-Null'
  - ps: c:\firebird\bin\fb_inet_server.exe -m -a
build:
  project: NETProvider\src\NETProvider.sln
  parallel: true
  verbosity: minimal
test_script:
  - nunit-console.exe ".\NETProvider\src\FirebirdSql.Data.UnitTests\bin\%Configuration%\FirebirdSql.Data.UnitTests.dll" /framework:net-4.0 /exclude=Local
artifacts:
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.dll
  - path: NETProvider\src\FirebirdSql.Data.FirebirdClient\bin\$(Configuration)\FirebirdSql.Data.FirebirdClient.pdb
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.dll
  - path: NETProvider\src\EntityFramework.Firebird\bin\$(Configuration)\EntityFramework.Firebird.pdb